<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_13677</name>
   <tag></tag>
   <elementGuidId>bbeed763-da6d-4457-aca4-006bce00de04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fromAccountId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fromAccountId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>82dd06ab-a455-4584-b4c3-fc69338db04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromAccountId</value>
      <webElementGuid>c7687861-d9cf-496c-959a-745a92aac1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3a70a12-d011-4da2-8e2b-c2710a982c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13677</value>
      <webElementGuid>3bf5c995-0ac9-4688-9f2c-b662610af05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromAccountId&quot;)</value>
      <webElementGuid>afaa2074-6beb-4abd-b601-acb5cff86e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fromAccountId']</value>
      <webElementGuid>76f4b591-83ec-45f2-a282-95e66cf61cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='openAccountForm']/form/select[2]</value>
      <webElementGuid>f87072cf-4d4a-48af-b84f-5e6e5f53606a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What type of Account would you like to open?'])[1]/following::select[2]</value>
      <webElementGuid>2716da39-efe7-48a8-a373-c8c05097bb35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open New Account'])[2]/following::select[2]</value>
      <webElementGuid>67f83d29-b2c4-4ce1-8c2b-9dcd8442bd92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Opened!'])[1]/preceding::select[1]</value>
      <webElementGuid>e632ab8b-dadb-4430-992d-321f70bc6280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your new account number:'])[1]/preceding::select[1]</value>
      <webElementGuid>dfb47de9-2d47-4171-b313-0dff2399eb17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>ffa04d1c-0b81-4ec6-878e-da7490961d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'fromAccountId' and (text() = '13677' or . = '13677')]</value>
      <webElementGuid>3d82929e-913f-4cb0-b152-2c69a7776522</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
